# Generated by Django 3.0.5 on 2020-05-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badge',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('PROFESSOR', 'professor'), ('MODERATOR', 'moderator'), ('ADMIN', 'admin'), ('FOUNDER', 'founder')], default='STUDENT', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='courses_completed',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lessons_completed',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
    ]
