# Generated by Django 3.0.5 on 2020-05-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200501_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='badge',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('PROFESSOR', 'Professor'), ('MODERATOR', 'Moderator'), ('ADMIN', 'Admin'), ('FOUNDER', 'Founder')], default='STUDENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='courses_completed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lessons_completed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
