# Generated by Django 3.0.5 on 2020-05-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.CharField(default='Anônimo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
